# SPDX-License-Identifier: MIT
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
core = (ROOT / "ledgertool" / "ledger_core.py").read_text(encoding="utf-8")
cli  = (ROOT / "ledgertool" / "ledger.py").read_text(encoding="utf-8")
licp = ROOT / "LICENSE"
lic  = licp.read_text(encoding="utf-8") if licp.exists() else ""

lic_cmt = "\n".join("# " + ln for ln in lic.splitlines()) if lic else ""
banner = (
    "#!/usr/bin/env python3\n"
    "# -*- coding: utf-8 -*-\n"
    "# SPDX-License-Identifier: MIT\n"
    "# GENERATED by scripts/bundle.py — DO NOT EDIT\n"
    + (("#\n" + lic_cmt + "\n") if lic_cmt else "")
)

out = (
    banner
    + "\n# === BEGIN ledger_core.py ===\n" + core + "\n# === END ledger_core.py ===\n\n"
    + "# === BEGIN ledger.py (CLI) ===\n" + cli + "\n# === END ledger.py ===\n"
)

dist = ROOT / "dist"
dist.mkdir(parents=True, exist_ok=True)
out_path = dist / "ledger.py"
out_path.write_text(out, encoding="utf-8")
print(out_path)
